### ISSUE TITLE
About arbitration mechanism

### ISSUE THREAD

**Issue by gmltjq2254** [IITP-Load-Balancing/computation_offloading_ROS2#1]
What is the role of the data arbitration mechanism?

**Comment by JUHO25** [comment]
The data arbitration mechanism executes the same task on both the local device and the server, then selects the result that is completed faster, minimizing the overall latency.

**Comment by JUHO25** [comment]
The data arbitration mechanism executes the same task on both the local device and the server, then selects the result that is completed faster, minimizing the overall latency.
